baseURL = "https://jarv.is/"
languageCode = "en-us"
title = "Jake Jarvis"

# increase timeout for image processing
timeout = 120000

canonifyURLs = true

disableKinds = ["taxonomy", "taxonomyTerm"]
disableHugoGeneratorInject = true   # don't worry, inserted manually :)

pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = false

enableRobotsTXT = true

# prefer Netlify's _redirects file, see outputs below
disableAliases = true

[params]
  description = "Hi there! I'm a frontend web developer based in Boston, Massachusetts specializing in modern JavaScript frameworks and progressive web apps."
  domain = "jarv.is"
  facebookAppID = "3357248167622283"
  gitRepo = "https://github.com/jakejarvis/jarv.is"
  defaultImage = "/me_large.jpg"
  copyrightFirstYear = "2001"
  wayback = "https://web.archive.org/web/20010501000000*/jakejarvis.com"

[author]
  name = "Jake Jarvis"
  jobTitle = "Front-End Web Developer"
  email = "jake@jarv.is"
  twitter = "jakejarvis"
  twitterID = "229769022"
  github = "jakejarvis"
  facebook = "jakejarvis"
  facebookID = "1329090853"
  instagram = "jakejarvis"
  linkedin = "jakejarvis"
  mastodon = "mastodon.social/@jakejarvis"

[outputs]
  home = ["HTML", "RSS", "MANIFEST", "REDIRECTS", "HEADERS"]
  section = ["HTML"]
  page = ["HTML", "AMP"]

[mediaTypes]
  [mediaTypes."text/netlify"]
    delimiter = ""

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss"
    baseName = "feed"
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp"
    path = "."
    permalinkable = true
    isHTML = true
  [outputFormats.MANIFEST]
    mediaType = "application/json"
    baseName = "manifest"
    notAlternative = true
  [outputFormats.REDIRECTS]
    mediaType = "text/netlify"
    baseName = "_redirects"
    isPlainText = true
    notAlternative = true
  [outputFormats.HEADERS]
    mediaType = "text/netlify"
    baseName = "_headers"
    isPlainText = true
    notAlternative = true

[sitemap]
  filename = "sitemap.xml"

[imaging]
  # options for resampling filters:
  # https://github.com/disintegration/imaging#image-resizing
  resampleFilter = "Linear"
  quality = 75

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      linkify = false
      strikethrough = true
      typographer = false
    [markup.goldmark.parser]
      autoHeadingID = false
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    tabWidth = 4

[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true
