baseURL = "https://jarv.is/"
languageCode = "en-us"
title = "Jake Jarvis"

# increase timeout for image processing (3 minutes)
timeout = 180000

canonifyURLs = true

pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = false

enableRobotsTXT = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# don't worry, inserted manually :)
disableHugoGeneratorInject = true

# prefer Netlify's _redirects file, see outputs below
disableAliases = true

[params]
  description = "Hi there! I'm a frontend web developer based in Boston, Massachusetts specializing in modern JavaScript frameworks and progressive web apps."
  domain = "jarv.is"
  pageMaxWidth = 910
  facebookAppID = "3357248167622283"
  gitRepo = "https://github.com/jakejarvis/jarv.is"
  defaultImage = "/me_large.jpg"
  copyrightFirstYear = "2001"
  wayback = "https://web.archive.org/web/20010501000000*/jakejarvis.com"
  license = "CC-BY-4.0"
  licenseFull = "Creative Commons Attribution 4.0 International"
  licenseURL = "https://creativecommons.org/licenses/by/4.0/"
  utterancesRepo = "jakejarvis/jarv.is"

[module]
  [[module.imports]]
    path = "github.com/twitter/twemoji"
    disabled = false
    [[module.imports.mounts]]
      source = "v/12.1.5"
      target = "static/vendor/emoji"

[author]
  name = "Jake Jarvis"
  jobTitle = "Front-End Web Developer"
  email = "jake@jarv.is"
  twitter = "jakejarvis"
  twitterID = "229769022"
  github = "jakejarvis"
  facebook = "jakejarvis"
  facebookID = "1329090853"
  instagram = "jakejarvis"
  linkedin = "jakejarvis"
  mastodon = "pogge.rs/@jake"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "&#x1F3E1;"
    url = "/"
    weight = -100
  [[menu.main]]
    name = "Notes"
    pre = "&#x1F4DD;"
    url = "/notes/"
    weight = -90
  [[menu.main]]
    name = "GitHub"
    pre = "&#x1F468;&#x200D;&#x1F4BB;"
    url = "https://github.com/jakejarvis"
    weight = -80
  [[menu.main]]
    name = "Email"
    pre = "&#x1F4EC;"
    # encode my email address like it's 2005 ( ͡° ͜ʖ ͡°)
    url = "&#x6D;&#x61;&#x69;&#x6C;&#x74;&#x6F;&#x3A;&#x6A;&#x61;&#x6B;&#x65;&#x40;&#x6A;&#x61;&#x72;&#x76;&#x2E;&#x69;&#x73;"
    weight = -70

[outputs]
  home = ["HTML", "RSS", "ALGOLIA", "MANIFEST", "REDIRECTS", "HEADERS"]
  section = ["HTML"]
  page = ["HTML", "AMP"]

[mediaTypes]
  [mediaTypes."text/netlify"]
    delimiter = ""

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss"
    baseName = "feed"
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp"
    path = "."
    permalinkable = true
    isHTML = true
  [outputFormats.ALGOLIA]
    mediaType = "application/json"
    baseName = "algolia"
    isPlainText = true
    notAlternative = true
  [outputFormats.MANIFEST]
    mediaType = "application/json"
    baseName = "manifest"
    isPlainText = true
    notAlternative = true
  [outputFormats.REDIRECTS]
    mediaType = "text/netlify"
    baseName = "_redirects"
    isPlainText = true
    notAlternative = true
  [outputFormats.HEADERS]
    mediaType = "text/netlify"
    baseName = "_headers"
    isPlainText = true
    notAlternative = true

[sitemap]
  filename = "sitemap.xml"

[imaging]
  # options for resampling filters:
  # https://github.com/disintegration/imaging#image-resizing
  resampleFilter = "Linear"
  quality = 75

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      linkify = false
      strikethrough = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = false
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    tabWidth = 4

[server]
  [[server.headers]]
    for = "/**"
    [server.headers.values]
      Access-Control-Allow-Origin = "*"
