baseURL = "https://jarv.is/"
languageCode = "en-us"
title = "Jake Jarvis"

disableKinds = ["taxonomy","taxonomyTerm","sitemap","RSS"]

[taxonomies]
  tag = ""
  category = ""

[permalinks]
    post = "/:year/:month/:day/:slug"

