baseURL = "https://jarv.is/"
languageCode = "en-us"
title = "Jake Jarvis"

# increase timeout for image processing (3 minutes)
timeout = 180000

canonifyURLs = true

pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = false

enableInlineShortcodes = true
enableRobotsTXT = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# don't worry, inserted manually :)
disableHugoGeneratorInject = true

# prefer Netlify's _redirects file, see outputs below
disableAliases = true

[params]
  description = "Hi there! I'm a frontend web developer based in Boston, Massachusetts specializing in the JAMstack, modern JavaScript frameworks, and progressive web apps."
  domain = "jarv.is"
  mainSection = "notes"
  pageMaxWidth = 940
  defaultImage = "img/me_large.jpg"
  github = "jakejarvis/jarv.is"
  facebookAppID = "3357248167622283"
  webmention = "jarv.is"
  copyrightFirstYear = "2001"
  license = "CC-BY-4.0"
  licenseFull = "Creative Commons Attribution 4.0 International"

[author]
  name = "Jake Jarvis"
  jobTitle = "Front-End Web Developer"
  email = "jake@jarv.is"
  twitter = "jakejarvis"
  twitterID = "229769022"
  github = "jakejarvis"
  facebook = "jakejarvis"
  facebookID = "1329090853"
  instagram = "jakejarvis"
  linkedin = "jakejarvis"
  mastodon = "mastodon.social/@jakejarvis"

[module]
  [[module.imports]]
    path = "github.com/twitter/twemoji"
    disable = false
    [[module.imports.mounts]]
      source = "assets/svg"
      target = "static/vendor/emoji/svg"

[frontmatter]
  lastmod = ["date", "publishDate", ":default"]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "&#x1F3E1;"
    url = "/"
    weight = -100
  [[menu.main]]
    name = "Notes"
    pre = "&#x1F5D2;"
    url = "/notes/"
    weight = -90
  [[menu.main]]
    name = "Projects"
    pre = "&#x1F468;&#x200D;&#x1F4BB;"
    url = "https://github.com/jakejarvis"
    weight = -80
  [[menu.main]]
    name = "Email"
    pre = "&#x1F4EC;"
    # encode my email address like it's 2005 ( ͡° ͜ʖ ͡°)
    url = "&#x6D;&#x61;&#x69;&#x6C;&#x74;&#x6F;&#x3A;&#x6A;&#x61;&#x6B;&#x65;&#x40;&#x6A;&#x61;&#x72;&#x76;&#x2E;&#x69;&#x73;"
    weight = -70

[outputs]
  home = ["HTML", "RSS", "ATOM", "ALGOLIA", "MANIFEST", "REDIRECTS", "HEADERS"]
  section = ["HTML"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss"
    baseName = "feed"   # /feed.xml
  [outputFormats.ATOM]
    mediaType = "application/atom+xml"
    baseName = "feed"   # /feed.atom
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp"   # amp.html
    path = "."   # put in same directory as original post
    permalinkable = true
    isHTML = true
  [outputFormats.ALGOLIA]
    mediaType = "application/json"
    baseName = "algolia"   # /algolia.json
    isPlainText = true
    notAlternative = true
  [outputFormats.MANIFEST]
    mediaType = "application/manifest+json"   # https://github.com/w3c/manifest/issues/689
    baseName = "site"   # /site.webmanifest
    isPlainText = true
    notAlternative = true
  [outputFormats.REDIRECTS]
    mediaType = "text/netlify"
    baseName = "_redirects"
    isPlainText = true
    notAlternative = true
  [outputFormats.HEADERS]
    mediaType = "text/netlify"
    baseName = "_headers"
    isPlainText = true
    notAlternative = true

[mediaTypes]
  [mediaTypes."application/atom+xml"]
    suffixes = ["atom"]
  [mediaTypes."application/manifest+json"]
    suffixes = ["webmanifest"]
  [mediaTypes."text/netlify"]
    delimiter = ""   # no extension for _headers & _redirects files

[sitemap]
  filename = "sitemap.xml"
  priority = 0.5

[imaging]
  # options for resampling filters:
  # https://github.com/disintegration/imaging#image-resizing
  resampleFilter = "Lanczos"
  # let imagemin do all the heavy lifting post-build
  quality = 100

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      linkify = false
      strikethrough = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = false
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    tabWidth = 4

[server]
  [[server.headers]]
    for = "/**"
    [server.headers.values]
      Access-Control-Allow-Origin = "*"
