baseURL = "/"
languageCode = "en-us"
title = "Jake Jarvis"

# increase timeout for image processing (3 minutes)
timeout = 180000

canonifyURLs = true

pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = false

enableInlineShortcodes = true
enableRobotsTXT = true

# as of v0.73.0: taxonomy => term, taxonomyTerm => taxonomy
# https://github.com/gohugoio/hugo/releases/tag/v0.73.0
disableKinds = ["taxonomy", "term"]

# don't worry, inserted manually :)
disableHugoGeneratorInject = true

# prefer 301 server redirects, see vercel.json
disableAliases = true

[params]
  description = "Hi there! I'm a frontend web developer based in Boston, Massachusetts specializing in the JAMstack, modern JavaScript frameworks, and progressive web apps."
  image = "images/logo.png"  # relative to assetDir root
  mainSection = "notes"  # content that appears in feeds
  baseURL = "https://jarv.is"  # different from baseURL above, this is only used where necessary
  [params.theme]
    maxWidth = 865  # px
    defaultTheme = "light"  # light or dark?
  [params.license]
    name = "CC-BY-4.0"
    nameLong = "Creative Commons Attribution 4.0 International"
    copyrightFirstYear = 2001
  [params.social]
    githubRepo = "jakejarvis/jarv.is"  # user/repo
    webmentionIO = "jarv.is"  # webmention.io username
    facebookAppID = 3357248167622283

[author]
  name = "Jake Jarvis"
  image = "images/me.jpg"  # relative to assetDir root
  email = "jake@jarv.is"
  [author.social]
    github = "jakejarvis"
    keybase = "jakejarvis"
    twitter = "jakejarvis"
    twitterID = 229769022
    medium = "jakejarvis"
    linkedin = "jakejarvis"
    facebook = "jakejarvis"
    facebookID = 1329090853
    instagram = "jakejarvis"
    mastodon = "mastodon.social/@jakejarvis"

[frontmatter]
  lastmod = ["date", "publishDate", ":default"]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "üè°"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Notes"
    pre = "üóí"
    url = "/notes/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    pre = "üë®‚Äçüíª"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    pre = "üì¨"
    # encode my email address like it's 2005 ( Õ°¬∞ Õú ñ Õ°¬∞)
    url = "&#x6D;&#x61;&#x69;&#x6C;&#x74;&#x6F;&#x3A;&#x6A;&#x61;&#x6B;&#x65;&#x40;&#x6A;&#x61;&#x72;&#x76;&#x2E;&#x69;&#x73;"
    weight = 4

[outputs]
  home = ["HTML", "RSS", "ATOM", "MANIFEST"]
  section = ["HTML"]
  page = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss"
    baseName = "feed"   # /feed.xml
    isPlainText = false
    isHTML = false
  [outputFormats.ATOM]
    mediaType = "application/atom+xml"
    baseName = "feed"   # /feed.atom
    isPlainText = false
    isHTML = false
  [outputFormats.MANIFEST]
    mediaType = "application/manifest+json"   # https://github.com/w3c/manifest/issues/689
    baseName = "site"   # /site.webmanifest
    isPlainText = true
    notAlternative = true

[mediaTypes]
  [mediaTypes."application/atom+xml"]
    suffixes = ["atom"]
  [mediaTypes."application/manifest+json"]
    suffixes = ["webmanifest"]

[sitemap]
  filename = "sitemap.xml"

[imaging]
  # options for resampling filters:
  # https://github.com/disintegration/imaging#image-resizing
  resampleFilter = "Lanczos"
  # let imagemin do all the heavy lifting post-build.
  # can be overridden (overrode?) inline for individual JPEGs:
  # https://gohugo.io/content-management/image-processing/#jpeg-quality
  quality = 100

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      linkify = false
      strikethrough = true
      typographer = false
    [markup.goldmark.parser]
      autoHeadingID = false
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    tabWidth = 4

# commit things like oEmbed JSON (tweets, etc.) next to resources in this repo
[caches]
  [caches.assets]
    dir = ":cacheDir/:project"  # default: :resourceDir/_gen
  [caches.getcsv]
    dir = ":resourceDir/_gen"   # default: :cacheDir/:project
  [caches.getjson]
    dir = ":resourceDir/_gen"   # default: :cacheDir/:project
  [caches.images]
    dir = ":resourceDir/_gen"
  [caches.modules]
    dir = ":cacheDir/modules"

[build]
  noJSConfigInAssets = true
  writeStats = true
  # don't use cache for SCSS compilation, better to throw error than be stale
  useResourceCacheWhen = "never"
