baseURL = "https://jarv.is/"
languageCode = "en-us"
title = "Jake Jarvis"

# increase timeout for image processing
timeout = 120000

canonifyURLs = true

disableFastRender = true
disableHugoGeneratorInject = true   # don't worry, inserted manually :)
disableKinds = ["taxonomy", "taxonomyTerm"]

pygmentsUseClasses = true
pygmentsCodeFences = true

enableRobotsTXT = true

# prefer Netlify's _redirects file, see outputs below
disableAliases = true

[author]
  name = "Jake Jarvis"
  email = "jake@jarv.is"
  twitter = "@jakejarvis"
  github = "jakejarvis"
  facebook = "jakejarvis"
  facebook_id = "1329090853"

[params]
  domain = "jarv.is"
  facebook_app_id = "3357248167622283"
  gitRepo = "https://github.com/jakejarvis/jarv.is"
  wayback = "https://web.archive.org/web/20010501000000*/jakejarvis.com"
  copyrightFirstYear = "2001"

[outputs]
  home = ["HTML", "RSS", "MANIFEST", "REDIRECTS", "HEADERS"]
  section = ["HTML"]
  page = ["HTML", "AMP"]

[mediaTypes]
  [mediaTypes."text/netlify"]
    delimiter = ""

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    basename = "amp"
    path = "."
    permalinkable = true
    isHTML = true
  [outputFormats.MANIFEST]
    mediaType = "application/json"
    baseName = "manifest"
    notAlternative = true
  [outputFormats.REDIRECTS]
    mediatype = "text/netlify"
    baseName = "_redirects"
    isPlainText = true
    notAlternative = true
  [outputFormats.HEADERS]
    mediatype = "text/netlify"
    baseName = "_headers"
    isPlainText = true
    notAlternative = true

[sitemap]
  filename = "sitemap.xml"

[imaging]
  # options for resampling filters:
  # https://github.com/disintegration/imaging#image-resizing
  resampleFilter = "Linear"
  quality = 75

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true
  # noopenerLinks = true       # requires custom fork w/ custom blackfriday: https://github.com/jakejarvis/hugo/tree/noopener
  plainIDAnchors = true
  fractions = false

[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true
