baseURL = "https://jarv.is/"
languageCode = "en-us"
title = "Jake Jarvis"

# increase timeout for image processing
timeout = 60000

canonifyURLs = true

disableFastRender = true
disableHugoGeneratorInject = true   # don't worry, inserted manually :)
disableKinds = ["taxonomy", "taxonomyTerm"]

pygmentsUseClasses = true
pygmentsCodeFences = true

enableRobotsTXT = true

[author]
  name = "Jake Jarvis"
  email = "jake@jarv.is"
  twitter = "@jakejarvis"
  github = "jakejarvis"

[params]
  domain = "jarv.is"
  gitRepo = "https://github.com/jakejarvis/jarv.is"
  wayback = "https://web.archive.org/web/20010501000000*/jakejarvis.com"
  copyrightFirstYear = "2001"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[sitemap]
  filename = "sitemap.xml"

[imaging]
  # options for resampling filters:
  # https://github.com/disintegration/imaging#image-resizing
  resampleFilter = "Linear"
  quality = 100

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true
  noopenerLinks = true       # requires custom fork w/ custom blackfriday: https://github.com/jakejarvis/hugo/tree/noopener
  plainIDAnchors = true
  fractions = false

[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true
