name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
        lfs: false
    - uses: jakejarvis/hugo-build-action@develop-v0.53-DEV
    - uses: actions/upload-artifact@master
      with:
        name: public
        path: './public'
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete --follow-symlinks
      env:
        SOURCE_DIR: './public'
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: 'jarv.is'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - uses: jakejarvis/cloudflare-serverless-action@master
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_AUTH_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
        CLOUDFLARE_AUTH_KEY: ${{ secrets.CLOUDFLARE_KEY }}
        CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_WORKER_NAME: 'jarv-is'
        CLOUDFLARE_SCRIPT_NAME: 'worker'
    - uses: jakejarvis/cloudflare-purge-action@master
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
        CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_KEY }}
    - run: sleep 30s
    - uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://jarv.is/'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
